Repository Yammy-expedition/frontend, pull requests merged in 2024-12, with the labels that each got.

#29 사이드바/메인페이지/메뉴페이지/글쓰기페이지 반응형 추가
  package-lock.json
  package.json
  src/App.css
  src/App.tsx
  src/assets/icons/common/hamburgermenu.svg
  src/assets/icons/menu/bookmark.svg
  src/components/common/Hamburger.tsx
  src/components/common/SideBar.tsx
  src/components/main/MapBox.tsx
  src/components/main/MarketRestaurantBox.tsx
  src/components/main/Search.tsx
  src/components/main/SearchBar.tsx
  src/components/main/WorldMap.tsx
  src/components/menu/common/PageNation.tsx
  src/components/menu/common/PostComment.tsx
  src/components/menu/common/PostContent.tsx
  src/components/menu/common/PostInfoTitle.tsx
  src/components/menu/common/PostingList.tsx
  src/components/menu/common/Search.tsx
  src/components/sing-up/NoEmailForm.tsx
  src/constants/quillModules.ts
  src/index.css
  src/pages/main/MainPage.tsx
  src/pages/menu/EachMenuPage.tsx
  src/pages/menu/PostingDetailPage.tsx
  src/pages/menu/WritingPostPage.tsx
  src/pages/sign-up/SignUpPage.tsx
  src/types/posting.d.ts
  src/utils/menu/postBookmark.ts
  src/utils/menu/postPosting.ts
Labels: feature, chore, html&css

#30 Sogang Map 완성
  public/images/logo.png
  public/index.html
  src/Router.js
  src/assets/icons/tips-for-sogang/exit.svg
  src/components/common/Footer.tsx
  src/components/my-page/MyDatas.tsx
  src/components/tips-for-sogang/KakaoMap.tsx
  src/components/tips-for-sogang/MapModal.tsx
  src/components/tips-for-sogang/SogangMap.tsx
  src/constants/.gitkeep
  src/constants/buildings.ts
  src/constants/openableBox.ts
  src/pages/chat/ChatMain.tsx
Labels: feature, api

#31 메인페이지 유저리스트 보여주기, 회원가입 반응형 적용
  public/index.html
  src/App.tsx
  src/assets/icons/menu/next.svg
  src/assets/icons/menu/prev.svg
  src/components/login/.gitkeep
  src/components/main/EachUserBox.tsx
  src/components/main/MapBox.tsx
  src/components/main/MarketRestaurantBox.tsx
  src/components/main/Search.tsx
  src/components/main/SearchBar.tsx
  src/components/menu/common/HeadComment.tsx
  src/components/menu/common/PostContent.tsx
  src/components/menu/common/PostInfoTitle.tsx
  src/components/menu/common/ReplyComment.tsx
  src/components/menu/market/MarketImageModal.tsx
  src/components/portal/MarketImagePortal.tsx
  src/components/sing-up/NoEmailForm.tsx
  src/components/sing-up/PersonalInformation.tsx
  src/components/sing-up/SelfCertification.tsx
  src/components/sing-up/TermsAndConditions.tsx
  src/components/sing-up/YesEmailForm.tsx
  src/constants/TermsAndConditionsText.ts
  src/index.css
  src/pages/main/MainPage.tsx
  src/pages/menu/PostingDetailPage.tsx
  src/pages/menu/WritingPostPage.tsx
  src/pages/sign-up/SignUpPage.tsx
  src/utils/main/getUserList.ts
  src/utils/menu/patchPosting.ts
Labels: feature, chore

#34 Tips for Sogang 미디어 쿼리 구현
  src/App.css
  src/Router.js
  src/assets/icons/chat/back.svg
  src/assets/icons/chat/chat.svg
  src/assets/icons/chat/more.svg
  src/assets/icons/chat/send.svg
  src/components/chat/ChatBubbles.tsx
  src/components/chat/ChatInput.tsx
  src/components/chat/ChatList.tsx
  src/components/common/SideBar.tsx
  src/components/tips-for-sogang/KakaoMap.tsx
  src/components/tips-for-sogang/MapModal.tsx
  src/components/tips-for-sogang/Restaurants.tsx
  src/constants/buildings.ts
  src/pages/chat/ChatDetail.tsx
  src/pages/chat/ChatMain.tsx
  src/pages/tips-for-sogang/TipsForSogangPage.tsx
  src/pages/what-is-unicon/WhatIsUnicon.tsx
  src/style/color.css
Labels: chore, html&css

#36 feat: 알림페이지 구현, 메인 페이지에서 유저 누르면 유저 페이지로 이동 구현
  src/Router.js
  src/api/instance.js
  src/assets/icons/main/notification.svg
  src/assets/icons/notification/trash-can-regular.svg
  src/components/common/MenuGroup.tsx
  src/components/main/EachUserBox.tsx
  src/components/main/SearchBar.tsx
  src/components/menu/common/PostContent.tsx
  src/components/menu/common/PostingList.tsx
  src/components/menu/market/MarketImageModal.tsx
  src/constants/openableBox.ts
  src/pages/menu/PostingDetailPage.tsx
  src/pages/notification/Notification.tsx
  src/pages/user-profile/UserProfile.tsx
  src/types/notification.d.ts
  src/types/user.d.ts
  src/utils/notification/deleteAllNotification.ts
  src/utils/notification/deleteNotification.ts
  src/utils/notification/getNotification.ts
  src/utils/notification/putReadNotification.ts
Labels: feature, api

#37 feat: chat starting
  src/components/chat/ChatBubbles.tsx
  src/components/chat/ChatInput.tsx
  src/components/chat/ChatList.tsx
  src/components/my-page/MyProfile.tsx
  src/components/my-page/ToChatButton.tsx
  src/pages/chat/ChatDetail.tsx
Labels: feature, api

#38 fix: 노티피케이션 링크 파싱
  src/pages/notification/Notification.tsx
Labels: fix, chore, api

#40 fix: 북마크 버그 수정, 아이콘 교체, 위치 조정
  src/assets/icons/menu/bookmark-regular.svg
  src/assets/icons/menu/bookmark-solid.svg
  src/components/menu/common/PostContent.tsx
  src/components/menu/common/PostInfoTitle.tsx
  src/pages/menu/PostingDetailPage.tsx
  src/utils/menu/postBookmark.ts
  src/utils/menu/postPostingLike.ts
Labels: fix, chore, api

#41 대대적 스타일링
  src/App.tsx
  src/assets/icons/main/sparkle.svg
  src/components/chat/ChatList.tsx
  src/components/common/TitleBox.tsx
  src/components/main/EachUserBox.tsx
  src/components/main/MapBox.tsx
  src/components/main/MarketRestaurantBox.tsx
  src/components/main/SearchBar.tsx
  src/components/menu/common/PageNation.tsx
  src/components/menu/common/PostContent.tsx
  src/components/menu/common/PostInfoTitle.tsx
  src/components/menu/common/PostingList.tsx
  src/components/menu/common/Search.tsx
  src/components/my-page/MyDatas.tsx
  src/components/my-page/MyProfile.tsx
  src/components/my-page/ToChatButton.tsx
  src/components/tips-for-sogang/Restaurants.tsx
  src/pages/main/MainPage.tsx
  src/pages/menu/EachMenuPage.tsx
  src/pages/menu/PostingDetailPage.tsx
  src/pages/my-page/MyPage.tsx
  src/pages/notification/Notification.tsx
  src/pages/tips-for-sogang/TipsForSogangPage.tsx
  src/pages/user-profile/UserProfile.tsx
  src/pages/what-is-unicon/WhatIsUnicon.tsx
  src/style/color.css
Labels: fix, html&css

#43 fix: 로그인 모달 로그인 버튼 위치 조정
  src/components/login/LoginModal.tsx
Labels: html&css

#44 chore: 진심 사소한 사이드바 스타일링
  src/components/common/SideBar.tsx
Labels: chore

#45 채팅 sse 구현
  package-lock.json
  package.json
  src/components/chat/ChatBubbles.tsx
  src/components/chat/ChatInput.tsx
  src/components/chat/ChatList.tsx
  src/components/menu/common/HeadComment.tsx
  src/components/menu/common/ReplyComment.tsx
  src/components/my-page/MyProfile.tsx
  src/components/sing-up/PersonalInformation.tsx
  src/pages/chat/ChatDetail.tsx
  src/pages/my-page/MyPage.tsx
  src/pages/notification/Notification.tsx
  src/pages/user-profile/UserProfile.tsx
  src/types/user.d.ts
Labels: feature, chore, api

#46 chore: 노티피케이션 아이콘 수정, 포스팅 디테일 페이지 링크 수정
  src/Router.js
  src/assets/icons/notification/comment-solid.svg
  src/assets/icons/notification/flag-solid.svg
  src/assets/icons/notification/message-solid.svg
  src/assets/icons/notification/user-plus-solid.svg
  src/assets/icons/notification/user-tie-solid.svg
  src/components/chat/ChatList.tsx
  src/components/main/MarketRestaurantBox.tsx
  src/components/menu/common/PostingList.tsx
  src/components/my-page/MyDatas.tsx
  src/pages/menu/PostingDetailPage.tsx
  src/pages/menu/WritingPostPage.tsx
  src/pages/notification/Notification.tsx
Labels: chore

#47 feat: emergency (채팅 롤백)
  src/components/chat/ChatList.tsx
  src/pages/chat/ChatDetail.tsx
Labels: fix, help wanted

#48 Sogang Map 서치 기능
  public/images/logo.png
  public/images/logo.svg
  public/index.html
  src/assets/icons/tips-for-sogang/hospital.svg
  src/assets/icons/tips-for-sogang/map.svg
  src/assets/icons/tips-for-sogang/restaurants.svg
  src/assets/icons/tips-for-sogang/time.svg
  src/components/tips-for-sogang/KakaoMap.tsx
  src/components/tips-for-sogang/MapModal.tsx
  src/components/tips-for-sogang/Restaurants.tsx
  src/components/tips-for-sogang/SearchBox.tsx
  src/components/tips-for-sogang/SogangMap.tsx
  src/pages/tips-for-sogang/TipsForSogangPage.tsx
Labels: feature

#51 Feature/admin page#50
  public/index.html
  src/App.tsx
  src/Router.js
  src/assets/icons/admin/exit.svg
  src/assets/icons/admin/link.svg
  src/assets/icons/admin/minusUser.svg
  src/assets/icons/admin/report.svg
  src/assets/icons/admin/user.svg
  src/components/admin/AdminModal.tsx
  src/components/admin/AdminSideBar.tsx
  src/components/admin/AllReportedUsers.tsx
  src/components/admin/AllReports.tsx
  src/components/admin/AllUsers.tsx
  src/components/admin/ReportDetail.tsx
  src/components/admin/ReportModal.tsx
  src/components/portal/AdminModalPortal.tsx
  src/pages/admin-page/AdminPage.tsx
Labels: feature, html&css, api

#53 chore: 채팅 복구
  src/components/chat/ChatList.tsx
  src/pages/chat/ChatDetail.tsx
Labels: chore

#54 feat: emergency
  src/components/common/Footer.tsx
  src/components/common/MenuGroup.tsx
  src/components/common/SideBar.tsx
  src/components/common/TitleBox.tsx
  src/components/menu/common/PostInfoTitle.tsx
  src/components/menu/common/PostingList.tsx
  src/constants/openableBox.ts
  src/index.css
  src/pages/notification/Notification.tsx
  src/types/notification.d.ts
Labels: chore
