Repository Yammy-expedition/frontend, pull requests merged in 2024-11, with the labels that each got.

#9 Feature/main page#3
  src/assets/icon/world.svg
  src/components/main/MarketRestaurantBox.tsx
  src/components/main/MenuGroup.tsx
  src/components/main/SearchBar.tsx
  src/components/main/TitleBox.tsx
  src/components/main/WorldMap.tsx
  src/constants/openableBox.ts
  src/pages/main/MainPage.tsx
  src/style/color.css
Labels: feat

#10 Feature/sign up page#7
  .env
  package-lock.json
  package.json
  src/App.css
  src/Router.js
  src/api/instance.js
  src/components/common/SideBar.tsx
  src/components/main/MenuGroup.tsx
  src/components/main/TitleBox.tsx
  src/components/sing-up/CustomCalendar.tsx
  src/components/sing-up/NoEmailForm.tsx
  src/components/sing-up/PersonalInformation.tsx
  src/components/sing-up/SelfCertification.tsx
  src/components/sing-up/TermsAndConditions.tsx
  src/components/sing-up/YesEmailForm.tsx
  src/constants/TermsAndConditionsText.ts
  src/constants/ages.ts
  src/constants/languages.ts
  src/constants/majors.ts
  src/constants/mbti.ts
  src/constants/openableBox.ts
  src/constants/peopleMockData.ts
  src/pages/menu/GeneralDiscussionPage.tsx
  src/pages/menu/MarketsPage.tsx
  src/pages/menu/MenuPage.tsx
  src/pages/menu/RestaurantsPage.tsx
  src/pages/sing-up/SignUpPage.tsx
  src/types/user.d.ts
Labels: feat

#11 Feature/tips page#4
  src/components/tips-for-sogang/.gitkeep
  src/components/tips-for-sogang/Restaurants.tsx
  src/components/tips-for-sogang/SogangMap.tsx
  src/pages/tips-for-sogang/TipsForSogangPage.tsx
Labels: feat

#16 docs: readme init
  README.md
Labels: chore, docs

#17 Chore: PR template 생성
  .github/pull_request_template.md
Labels: chore, docs

#19 Feature/main page#3
  package-lock.json
  package.json
  public/output_world.svg
  public/world.svg
  src/assets/icons/book.svg
  src/assets/icons/cafe.svg
  src/assets/icons/coment.svg
  src/assets/icons/eye.svg
  src/assets/icons/heart.svg
  src/assets/icons/like.svg
  src/assets/icons/more.svg
  src/assets/icons/plus.svg
  src/assets/icons/printer.svg
  src/assets/icons/search.svg
  src/assets/icons/world.svg
  src/components/main/MapBox.tsx
  src/components/main/Search.tsx
  src/components/main/WorldMap.tsx
  svgo.config.js
Labels: feature, fix

#23 Feature/menu#8
  src/Router.js
  src/assets/icons/main/world.svg
  src/assets/icons/menu/comment.svg
  src/assets/icons/menu/eye.svg
  src/assets/icons/menu/heart.svg
  src/assets/icons/menu/like.svg
  src/assets/icons/menu/more.svg
  src/components/main/MarketRestaurantBox.tsx
  src/components/main/WorldMap.tsx
  src/components/menu/Comment.tsx
  src/components/sing-up/NoEmailForm.tsx
  src/components/sing-up/YesEmailForm.tsx
  src/constants/openableBox.ts
  src/pages/menu/GeneralDiscussionPage.tsx
  src/pages/menu/MarketsPage.tsx
  src/pages/menu/MenuPage.tsx
  src/pages/menu/PostingDetailPage.tsx
  src/pages/menu/RestaurantsPage.tsx
  src/pages/menu/WritingPostPage.tsx
  src/pages/sign-up/SignUpPage.tsx
  src/types/comment.d.ts
  src/utils/common/getPostingList.ts
  src/utils/menu/deletePosting.ts
  src/utils/menu/getPostingDetail.ts
  src/utils/menu/patchPosting.ts
  src/utils/menu/postComment.ts
  src/utils/menu/postPosting.ts
  src/utils/menu/postPostingLike.ts
  src/utils/menu/postPostingViewCount.ts
  src/utils/sign-up/postSendCode.ts
  src/utils/sign-up/postSubmitCode.ts
Labels: chore, docs

#24 Feature/menu#8
  package-lock.json
  package.json
  src/App.tsx
  src/AuthRoute.tsx
  src/Router.js
  src/api/instance.js
  src/assets/icons/main/world.svg
  src/assets/icons/menu/emptyLike.svg
  src/assets/icons/menu/filledLike.svg
  src/assets/icons/menu/smallMore.svg
  src/assets/icons/output_world.svg
  src/components/common/MenuGroup.tsx
  src/components/login/LoginModal.tsx
  src/components/main/MapBox.tsx
  src/components/main/MarketRestaurantBox.tsx
  src/components/main/WorldMap.tsx
  src/components/menu/Comment.tsx
  src/components/menu/common/HeadComment.tsx
  src/components/menu/common/PageNation.tsx
  src/components/menu/common/PostingList.tsx
  src/components/menu/common/Search.tsx
  src/pages/menu/EachMenuPage.tsx
  src/pages/menu/GeneralDiscussionPage.tsx
  src/pages/menu/MarketsPage.tsx
  src/pages/menu/MenuPage.tsx
  src/pages/menu/PostingDetailPage.tsx
  src/pages/menu/RestaurantsPage.tsx
  src/pages/menu/WritingPostPage.tsx
  src/types/comment.d.ts
  src/types/js-cookie.d.ts
  src/types/posting.d.ts
  src/utils/common/getUserInfo.ts
  src/utils/deletePosting.ts
  src/utils/menu/postCommentLike.ts
  src/utils/patchPosting.ts
  src/utils/postComment.ts
Labels: feature, refactor, api

#25 Restaurant API 연동, Loading 컴포넌트
  package-lock.json
  package.json
  public/images/loading.gif
  public/images/tips-for-sogang/google-map.png
  public/images/tips-for-sogang/naver-map.png
  src/Router.js
  src/api/.gitkeep
  src/assets/icons/tips-for-sogang/book.svg
  src/assets/icons/tips-for-sogang/cafe.svg
  src/assets/icons/tips-for-sogang/printer.svg
  src/components/admin-page/.gitkeep
  src/components/admin/TipsRestaurants.tsx
  src/components/common/Footer.tsx
  src/components/common/Loading.tsx
  src/components/my-page/.gitkeep
  src/components/my-page/MyProfile.tsx
  src/components/tips-for-sogang/Restaurants.tsx
  src/components/tips-for-sogang/SogangMap.tsx
  src/pages/admin-page/AdminPage.tsx
  src/pages/my-page/MyPage.tsx
  src/pages/tips-for-sogang/TipsForSogangPage.tsx
  src/setupTests.ts
  src/types/.gitkeep
  src/utils/.gitkeep
  src/utils/menu/postPosting.ts
  tsconfig.json
Labels: feature, fix, api

#27 마이페이지 정보 수정 빼고 완
  .env
  package-lock.json
  package.json
  public/images/my-page/certified.png
  public/images/my-page/initProfile.png
  public/images/my-page/initProfile2.png
  src/Router.js
  src/assets/icons/my-page/cake.svg
  src/assets/icons/my-page/email.svg
  src/assets/icons/my-page/eye.svg
  src/assets/icons/my-page/heart.svg
  src/assets/icons/my-page/language.svg
  src/assets/icons/my-page/major.svg
  src/assets/icons/my-page/mbti.svg
  src/assets/icons/my-page/person.svg
  src/components/my-page/MyDatas.tsx
  src/components/my-page/MyProfile.tsx
  src/pages/my-page/MyPage.tsx
  src/utils/my-page/findInfos.ts
Labels: feature, html&css, api
